title: Chilba Cristian - CV
description: Personal CV
theme: jekyll-theme-minimal

# Optional: add your GitHub and LinkedIn links for the footer
github_username: cristichilba
linkedin_username: cristian-chilba


